// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALzSeNG2v32wfm3QPgaF7-cbAW_92rlVY',
    appId: '1:93573013242:web:ad22f29550ebf41f5df343',
    messagingSenderId: '93573013242',
    projectId: 'instagram-clone-747fa',
    authDomain: 'instagram-clone-747fa.firebaseapp.com',
    storageBucket: 'instagram-clone-747fa.appspot.com',
    measurementId: 'G-Y5Y9LC26BE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDcQYUUtJwNLTADrasNIVvhkmNjx8oERY',
    appId: '1:93573013242:android:4e74d46647aaead85df343',
    messagingSenderId: '93573013242',
    projectId: 'instagram-clone-747fa',
    storageBucket: 'instagram-clone-747fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSyuIdQ7QOOhcwd5Ykr-rJ2MNGhI5tFhY',
    appId: '1:93573013242:ios:6e68f3961373ae515df343',
    messagingSenderId: '93573013242',
    projectId: 'instagram-clone-747fa',
    storageBucket: 'instagram-clone-747fa.appspot.com',
    iosClientId: '93573013242-64b9ngnlf6qr7t535r5n3t5kbkqhg6ec.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSyuIdQ7QOOhcwd5Ykr-rJ2MNGhI5tFhY',
    appId: '1:93573013242:ios:6e68f3961373ae515df343',
    messagingSenderId: '93573013242',
    projectId: 'instagram-clone-747fa',
    storageBucket: 'instagram-clone-747fa.appspot.com',
    iosClientId: '93573013242-64b9ngnlf6qr7t535r5n3t5kbkqhg6ec.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
